Name:           ros-kinetic-ecl-mobile-robot
Version:        0.60.3
Release:        0%{?dist}
Summary:        ROS ecl_mobile_robot package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/ecl_mobile_robot
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-ecl-build
Requires:       ros-kinetic-ecl-errors
Requires:       ros-kinetic-ecl-formatters
Requires:       ros-kinetic-ecl-geometry
Requires:       ros-kinetic-ecl-license
Requires:       ros-kinetic-ecl-linear-algebra
Requires:       ros-kinetic-ecl-math
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-ecl-build
BuildRequires:  ros-kinetic-ecl-errors
BuildRequires:  ros-kinetic-ecl-formatters
BuildRequires:  ros-kinetic-ecl-geometry
BuildRequires:  ros-kinetic-ecl-license
BuildRequires:  ros-kinetic-ecl-linear-algebra
BuildRequires:  ros-kinetic-ecl-math

%description
Contains transforms (e.g. differential drive inverse kinematics) for the various
types of mobile robot platforms.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Nov 09 2016 Daniel Stonier <d.stonier@gmail.com> - 0.60.3-0
- Autogenerated by Bloom

* Tue May 03 2016 Daniel Stonier <d.stonier@gmail.com> - 0.60.1-0
- Autogenerated by Bloom

